# Uncomment the next line to define a global platform for your project
platform :osx, '10.12'

target 'metro-gallery' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for metro-gallery
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'SwiftHEXColors'
  pod 'FlexibleImage', '~> 1.9'
end
